# This file was automatically generated by makemake.rb.
# Any changes you make to this file will be overwritten
# whenever makemake is run.

PREFIX := /usr/local
BINDIR := $(PREFIX)/bin
INCDIR := $(PREFIX)/include
LIBDIR := $(PREFIX)/lib

default: release

build: force
	$(eval export BUILD)
	make -rf .makemake/Makefile build

release: release-setup build
release-setup: force
	$(eval export CXXFLAGS := -Wall -Wextra -Werror -O3 -fPIC)
	$(eval export BUILD := release)

debug: debug-setup build
debug-setup: force
	$(eval export CXXFLAGS := -Wall -Wextra -Werror -O0 -fPIC -g)
	$(eval export BUILD := debug)


install: release
	cp -f build/$(BUILD)/libRPN.so.0.1 $(LIBDIR)
	cp -f build/$(BUILD)/libRPN.so.0 $(LIBDIR)
	cp -f build/$(BUILD)/libRPN.so $(LIBDIR)
	cp -f build/$(BUILD)/RPN.h $(INCDIR)
	ldconfig -n $(LIBDIR)

uninstall:
	rm -f $(LIBDIR)/libRPN.so.0.1
	rm -f $(LIBDIR)/libRPN.so.0
	rm -f $(LIBDIR)/libRPN.so
	rm -f $(INCDIR)/RPN.h
	ldconfig -n $(LIBDIR)
	
check: chks
chks: force
	make -rf .makemake/Makefile chks

clean:
	rm -Rf build
	rm -Rf dep
force:
	true
