include ../../../../../flags.mk

DIRS = 
MOCS = 
OBJS = arccosecant arccosine arccotangent arcsecant arcsine arctangent cosecant cosine cotangent secant sine tangent

include ../../../../../common.mk
