#ifndef RPN_H
#define RPN_H

#ifdef RPN_LIBHEADER
/* Hack to keep the installed rpn.h header file (generated by g++ -E)
 * from including the standard system headers.  This makes sure you
 * get your system headers when compiling, and keeps rpn.h several
 * orders of magnitude smaller.
 */
	#define INCLUDE(hash, x) hash include <x>
	INCLUDE(#, cmath)
	INCLUDE(#, map)
	INCLUDE(#, stdexcept)
	INCLUDE(#, string)
	INCLUDE(#, vector)
#endif

#ifndef RPN_LIBHEADER
	#include <string>
#endif

#include "context.h"
#include "evaluator.h"
#include "exception.h"
#include "expression.h"
#include "nodes/inheritable.h"

namespace RPN
{
	namespace Constants
	{
		const double PI = 3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679;
		const double E  = 2.7182818284590452353602874713526624977572470936999595749669676277240766303535475945713821785251664274;
	}
	
	void initialize();
	bool isValidName(const std::string& name);
}

#endif

