include ../../../../../flags.mk

DIRS = 
MOCS = 
OBJS = arccosecant arccosine arccotangent arccotangent2 arcsecant arcsine arctangent arctangent2 cosecant cosine cotangent secant sine tangent

include ../../../../../common.mk
